### ISSUE TITLE
the login id 

### ISSUE THREAD

**Issue by hxrarkey** [derickfelix/BankApplication#9] opened 2023-01-09 14:30 UTC
wht is the user login id and passwrd i am not able to open it

**Comment by derickfelix** [comment] 2023-01-16 14:09
duplicate of #4

**Closed** 2023-01-16 14:11 UTC

**Comment by gokuyuan** [comment] 2025-01-22 01:10
1、The user id and password you provided in README.md cannot be logged in
2、what is id and password of database

**Comment by hxrarkey** [comment] 2025-01-22 03:13
it is admin as the user name 
and password is admin123
